import math
from src.geometry import *

SCREEN_SIZE = 900, 500, 100
SCREEN = Parallelepiped( (-SCREEN_SIZE[0]/2, -SCREEN_SIZE[1]/2, 0 ), 
                         SCREEN_SIZE[0], SCREEN_SIZE[1], SCREEN_SIZE[2])
FPS = 30
GAME_Z = 0
BG_COLOR = ( 0.2, 0, 0.2 ) 
BULLET_SPEED = int( SCREEN.w / (FPS*6) )
ASTEROIDS_SPEED = int( SCREEN.w / (FPS*15) )
ASTEROIDS_GROWN_RATIO = 1/30.0
DIFFICULTY = 1/6.0
KEYS_WEIGHT = int( SCREEN_SIZE[0] / (FPS*30) )
SHIP_SIZE = SCREEN_SIZE[0] * 1/90.0
ASTEROID_SIZE = SCREEN_SIZE[0] * 1/80.0
BULLET_SIZE = SCREEN_SIZE[0] *1/180.0
DIR_RATIO = int( BULLET_SPEED * 2.0 )
CANNON_SIZE = SHIP_SIZE / 3.0
CANNON_DIST = int( SCREEN_SIZE[0] * 1/60.0 )
INCUBATION = int( 2*ASTEROIDS_SPEED/3.0 )
SPLIT_N = 3
AST_DIR_ANG = math.pi
LEVEL_DEC = 1/2.0
FORM_NAME = "Asteroid GL"
CAMERA_EYE = 0, 0, 600
CAMERA_CENTER = 0, 0, GAME_Z
LIGHT_0_COLOR = 1, 1, 1, 1
LIGHT_0_POSITION = 0, 0, 100
FAR_VAL = CAMERA_EYE[2] + abs( GAME_Z ) + 100
NEAR_VAL = 1 
SPHERE_FINEST_COEFF = 1/2.0 
CANNON_QUALITY = 5
SHIP_COLOR = 1, 0, 0, 1
BULLET_COLOR = 0, 0, 1, 1
ASTEROID_COLOR = 0, 1, 0, 1
MAX_SHIP_SPEED = BULLET_SPEED
BULLET_CHARGE_TIMER = 0
BULLET_CHARGE_TIME = int( 1000 / FPS ) * 10
