import math
from OpenGL.GLUT import *
from OpenGL.GLU import *
from OpenGL.GL import *

from src.geometry import *

glutInit()

FULLSCREEN_MODE = True
if FULLSCREEN_MODE :
    SCREEN_SIZE =  glutGet( GLUT_SCREEN_WIDTH ), glutGet( GLUT_SCREEN_HEIGHT ), 500
else :
    SCREEN_SIZE =  900, 600, 500
SCREEN = Parallelepiped( (-SCREEN_SIZE[0]/2, -SCREEN_SIZE[1]/2, 0 ), 
                         SCREEN_SIZE[0], SCREEN_SIZE[1], SCREEN_SIZE[2])
FPS = 20
GAME_Z = 0
BG_COLOR = ( 0.2, 0, 0.2 ) 
BULLET_SPEED = int( SCREEN.w / (FPS*6) )
ASTEROIDS_SPEED = int( SCREEN.w / (FPS*8) )
ASTEROIDS_GROWN_RATIO = 1/60.0
DIFFICULTY = 1/4.0
KEYS_WEIGHT = int( SCREEN_SIZE[0] / (FPS*15) )
SHIP_SIZE = SCREEN_SIZE[0] * 1/90.0
ASTEROID_SIZE = SCREEN_SIZE[0] * 1/80.0
BULLET_SIZE = SCREEN_SIZE[0] *1/180.0
DIR_RATIO = int( BULLET_SPEED * 2.0 )
CANNON_SIZE = SHIP_SIZE / 3.0
CANNON_DIST = int( SCREEN_SIZE[0] * 1/60.0 )
INCUBATION = int( 2*ASTEROIDS_SPEED/3.0 )
SPLIT_N = 3
AUTO_FIRE_MODE = True
AST_DIR_ANG = math.pi
LEVEL_DEC = 1/2.0
FORM_NAME = "Asteroid GL"
CAMERA_EYE = 0, 0, 600
CAMERA_CENTER = 0, 0, GAME_Z
LIGHT_0_COLOR = 1, 1, 1, 1
LIGHT_0_POSITION = 0, 0, 200
FAR_VAL = CAMERA_EYE[2] + abs( GAME_Z ) + 100
NEAR_VAL = 1
CANNON_QUALITY = 5
SHIP_COLOR = 1, 0, 0, 1
BULLET_COLOR = 0, 0, 1, 1
ASTEROID_COLOR = 0, 1, 0, 1
MAX_SHIP_SPEED = BULLET_SPEED
BULLET_CHARGE_TIMER_VALUE = 0
BULLET_CHARGE_TIME = int( 1000 / FPS ) * 1
COLOR_DEPTH = 8
SHIP_QUALITY = 7.5
QUALITY_DIV = ASTEROID_SIZE / 3
ASTEROID_QUALITY_DEC = 0.01
MAX_ASTEROID_QUALITY = 1
CURRENT_ASTEROID_QUALITY = 1

